POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "a blog joy pagination",
  "postType": "story",
  "slug":"a-new-blog-after-you-you",
  "status": "draft",
  "content": " habi jabi content",
  "schema": "{\"key\":\"value\"}",
  "featuredImageUrl": "https://themewagon.freshdesk.com/a/dashboard/default",
  "tags": [1,6,8],
  "metaOptions": {
    "metaValue": "{\"title\":\"a nenene blog\", \"keywords\":\"habijabi, hisamar\"}"
  },
  "authorId": 1
}