POST http://localhost:3000/users
Content-Type: application/json

{
  "firstName": "Ghum", 
  "lastName": "doe", 
  "email" : "ghum@doe.com",
  "password": "Password222#"
}

POST http://localhost:3000/users/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiZ2h1bUBkb2UuY29tIiwiaWF0IjoxNzQxOTI3Nzg4LCJleHAiOjE3NDE5MzEzODgsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.hOGgbMqIvBLlXCUrht5sTZms8Jmcb7BA-sbhD0dbWh0
{
  "users": [
  {
  "firstName": "ghon", 
  "lastName": "doe", 
  "email": "joybangla@gmail.com",
  "password": "Password222#"
},
{
  "firstName": "ghon", 
  "lastName": "doe", 
  "email": "ghon@gmail.com",
  "password": "Password222#"
}
]
}

