POST http://localhost;3000/auth/refreash-tokens
Content-Type: appication/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiZ2h1bUBkb2UuY29tIiwiaWF0IjoxNzQyMzc4MTU4LCJleHAiOjE3NDIzODE3NTgsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.LQAdw2oAlSUnN6Cf0nO0GPXjYUPP3Wp3O97nf6LsXQQ

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTc0MjM3ODE1OCwiZXhwIjoxNzQyMzg2NzU4LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.cG-0kUhzAsshNTjTFDkBYhBmDYhNOkGmxx0pMGvJAMQ",
}