POST http://localhost:3000/tags
Content-Type: application/json

{
  "name": "obhaasdijou",
  "slug": "bookasass.com",
  "description": "this is a new tag",
  "schema": "{\"key\":\"value\"}",
  "featureImage": "www.featureima.com"
}